### PR TITLE
Add developer docs

### PR DESCRIPTION
**Pull request by octylFractal**
This PR adds the long-awaited developer documentation for WorldEdit.

This PR is currently under construction, but feedback is still requested to ensure that the documentation is understandable.

Preview at: https://octyl.net/engine-hub/WorldEditDocs-preview/api/

### CODE REVIEW

**Comment by wizjany** [comment]
Initial thoughts:
I like the separation between concept and example, and linking the used concepts in example pages.
I think the entire abstraction layer should be a concept page, and maybe have some examples of adapter usage.
Not sure if it's mentioning some more details in the game like the default pastebuilder settings? eg entities are copied by default and air is not ignored by default, but the clipboard examples set both of those things (to the default).

**Comment by JOO200** [comment]
Maybe link the source code from the current commands as examples?
Most of the things are covered in those commands, for the usage from external plugins there are only small adjustment (get LocalSession, EditSession etc.)

**Comment by octylFractal** [comment]
I would rather not, there is a lot of unnecessary code and handling in the command methods that will distract from the examples.

**Comment by octylFractal** [comment]
I think that while this may not provide full documentation, it provides a good start, and can be contributed to more easily. I'd like to merge this with the content it has now, but if there are comments on the existing content, I'd be happy to incorporate them. Expansions can be handled as either direct commits (EH members) or PRs (others).

**Pull request merged**
