### PR TITLE
Reorganization and addition of info on WorldEditCUI for Forge

### PR DESCRIPTION
**Pull request by Eric-01**
Basically what's written in the title :)

### CODE REVIEW

**Comment by wizjany** [comment]
we're not going to recommend the "forge edition" mod. it's completely independent, the author has knowingly stolen code in the past, and they now heavily obfuscate their mod in response to being called out on it. also it's been reported to cause various issues.

**Comment by Eric-01** [comment]
Okay, I understand. What do you think about the reorganization itself?

**Comment by wizjany** [comment]
I initially wrote the drawsel part as a separate tip rather than a direct alternative because while it's nice to have it really doesn't compare to the completeness of the CUI mod. I don't really care if they are numbered 1/2 or as a main section with a tip tbh, that was just the way I view the two options.

**Comment by Eric-01** [comment]
Some people may not select large areas, but would like to see visual feedback without having to download yet another mod, so the built-in server-side highlighting will be sufficient for them. I feel it would be better to write about it as a real alternative.

**Pull request closed without merging**
